[tool.poetry]
name = "pyautoppt"
version = "0.1.0"
description = ""
authors = ["wn0x00 <320753691@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pywin32 = "^304"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
